from typing import Protocol


class StorageAccessor(Protocol):
    """ストレージアクセサー(Query操作)"""

    def list_files(self, path: str, recursive: bool = False) -> list[str]: ...

    def exists(self, path: str, *, follow_symlinks: bool = True) -> bool: ...

    def get_size(self, path: str) -> int: ...

    def read_file(self, path: str, mode: str = "r") -> str | bytes: ...


class StorageOperator(Protocol):
    """ストレージオペレーター(Command操作)"""

    def copy(self, source: str, destination: str, overwrite: bool = False, create_parents: bool = True) -> str: ...

    def delete(self, path: str, recursive: bool = False) -> None: ...

    def move(self, source: str, destination: str, overwrite: bool = False, create_parents: bool = True) -> str: ...


class Storage(Protocol):
    # --- query operations(side-effect free) ---
    def list_files(self, path: str, recursive: bool = False) -> list[str]: ...

    def exists(self, path: str, *, follow_symlinks: bool = True) -> bool: ...

    def get_size(self, path: str) -> int:
        """ファイルサイズ（バイト数）を取得する"""
        ...

    def read_file(self, path: str, mode: str = "r") -> str | bytes: ...

    # --- command operations(side-effect) ---
    def copy(self, source: str, destination: str, overwrite: bool = False, create_parents: bool = True) -> str: ...

    def delete(self, path: str, recursive: bool = False) -> None: ...

    def move(self, source: str, destination: str, overwrite: bool = False, create_parents: bool = True) -> str: ...
